# Generated by Django 4.2.3 on 2024-08-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoverPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("background_image", models.ImageField(upload_to="cover_images/")),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
            ],
        ),
    ]
