# Generated by Django 4.2.3 on 2024-08-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="A brief description, max 150 words.", max_length=150
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(help_text="Date of birth in YYYY-MM-DD format."),
                ),
                (
                    "phone_number",
                    models.CharField(help_text="Contact phone number.", max_length=15),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address.", max_length=254, unique=True
                    ),
                ),
                ("address", models.TextField(help_text="Residential address.")),
                (
                    "upload_cv",
                    models.FileField(
                        help_text="Upload your CV in PDF or DOC format.",
                        upload_to="cvs/",
                    ),
                ),
            ],
        ),
    ]
