# Generated by Django 4.2.3 on 2024-08-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.CharField(help_text="Residential address.", max_length=70),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="description",
            field=models.TextField(help_text="A brief description, max 150 words."),
        ),
    ]
