# Generated by Django 4.2.3 on 2024-08-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_userprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture.",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
