# Generated by Django 4.2.3 on 2024-08-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_expertise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertise",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="The end date of the expertise.", null=True
            ),
        ),
    ]
