# Generated by Django 4.2.3 on 2024-08-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_expertise_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="The start date of the education."),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="The end date of the education (optional).",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the education, e.g., Master, Bachelor of Information Technology.",
                        max_length=200,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="A brief description of the education.",
                        max_length=500,
                    ),
                ),
            ],
        ),
    ]
